### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by LiuHanHsiang** [ArmDeveloperEcosystem/ml-object-detection-examples-for-imx93#2]
I'm using TrafficCamNet ONNX Model from [Nvidia NGC](https://catalog.ngc.nvidia.com/orgs/nvidia/teams/tao/models/trafficcamnet/files?version=pruned_onnx_v1.0.3) 

I convert the onnx into tflite model using [model_conversion.ipynb](https://github.com/ArmDeveloperEcosystem/ml-object-detection-examples-for-imx93/blob/main/detectnet_v2/model_conversion.ipynb)

 when I try to run  `python main.py  resnet18_trafficcamnet_pruned.tflite` it happened
 
//////////////////////////////////
pad 0.0
convert 15.628576278686523
predict 46.76985740661621
post process 0.0
nms 0.0
nms 0.0
nms 0.0
Traceback (most recent call last):
  File ".\main.py", line 67, in <module>
    max_output_sizes[label],
IndexError: list index out of range 
/////////////////////////////////

 .tflite file screenshot of the model in Netron.app
![resnet18_trafficcamnet_pruned tflite](https://github.com/ArmDeveloperEcosystem/ml-object-detection-examples-for-imx93/assets/57740647/1c891675-fb3b-4895-b678-4ffb860b8b39)

**Comment by LiuHanHsiang** [comment]
ok i figured it out by changing main.py 
colors
max_output_sizes 
iou_thresholds 
score_thresholds
with 4 indexs

**Comment by sandeepmistry** [comment]
Hi @LiuHanHsiang,

Excellent, thanks for the update, great to hear you have this working!
